name: "Testing package"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 1"

jobs:
  helloworld:
    runs-on: ubuntu-24.04

    steps:
      - name: Greetings from Github Actions
        shell: python
        run: |
          print("Hello World")
      
      - name: Check out the repository
        uses: actions/checkout@v7
    
      - name: Setting up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      
      - name: Install package
        run: |
          python -m pip install .
          python -m pip install -r requirements-dev.txt
      
      - name: Run Python Tests
        run: python -m pytest